// <auto-generated />
using System;
using KidMonitor.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KidMonitor.Core.Data.Migrations
{
    [DbContext(typeof(KidMonitorDbContext))]
    [Migration("20260404143801_AddPendingCloudEvents")]
    partial class AddPendingCloudEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.3");

            modelBuilder.Entity("KidMonitor.Core.Models.AppSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessName");

                    b.HasIndex("StartedAt");

                    b.ToTable("AppSessions");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.ContentSession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("AppSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentIdentifier")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContentTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DurationSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppSessionId");

                    b.HasIndex("StartedAt");

                    b.ToTable("ContentSessions");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.ContentSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CapturedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CapturedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContentSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ContentType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceUrl")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("ContentSessionId");

                    b.ToTable("ContentSnapshots");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.DailySummary", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppBreakdownJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FoulLanguageEventCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HtmlReportPath")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ReportDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalScreenTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ReportDate")
                        .IsUnique();

                    b.ToTable("DailySummaries");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.LanguageDetectionEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AppName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("ContentSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContextSnippet")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DetectedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MatchedTerm")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ContentSessionId");

                    b.HasIndex("DetectedAt");

                    b.ToTable("LanguageDetectionEvents");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.NotificationLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AppSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Delivered")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AppSessionId");

                    b.HasIndex("SentAt");

                    b.ToTable("NotificationLogs");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.PendingCloudEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("EnqueuedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EnqueuedAt");

                    b.ToTable("PendingCloudEvents");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.ContentSession", b =>
                {
                    b.HasOne("KidMonitor.Core.Models.AppSession", "AppSession")
                        .WithMany()
                        .HasForeignKey("AppSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppSession");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.ContentSnapshot", b =>
                {
                    b.HasOne("KidMonitor.Core.Models.ContentSession", "ContentSession")
                        .WithMany("Snapshots")
                        .HasForeignKey("ContentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContentSession");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.LanguageDetectionEvent", b =>
                {
                    b.HasOne("KidMonitor.Core.Models.ContentSession", "ContentSession")
                        .WithMany()
                        .HasForeignKey("ContentSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ContentSession");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.NotificationLog", b =>
                {
                    b.HasOne("KidMonitor.Core.Models.AppSession", "AppSession")
                        .WithMany()
                        .HasForeignKey("AppSessionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("AppSession");
                });

            modelBuilder.Entity("KidMonitor.Core.Models.ContentSession", b =>
                {
                    b.Navigation("Snapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
